version: '3.8'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
    volumes:
      - .:/var/www/symfony_docker

  database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony_docker
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - '4306:3306'
      volumes:
        - ./dbdata:/var/lib/mysql
